default_language_version:
  python: python3.13
default_stages: [pre-commit]
default_install_hook_types: [pre-commit, prepare-commit-msg]
repos:
  - repo: meta
    hooks:
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: check-ast
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: ".*\\.cmake"
    - id: check-docstring-first
    - id: check-yaml
      exclude: ".clang-format"
      args: [--allow-multiple-documents]
    - id: check-json
    - id: debug-statements
    - id: check-added-large-files
      args: [--maxkb=1024]
      exclude_types:
          - png
          - jpeg
          - pdf
    - id: check-shebang-scripts-are-executable
      exclude_types:
        - batch
    - id: check-executables-have-shebangs
      exclude_types:
        - batch
    - id: check-merge-conflict
    - id: mixed-line-ending
      args: [--fix=lf]
      exclude_types:
        - powershell
        - batch
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
    - id: mdformat
      language_version: python3
      additional_dependencies:
          - linkify-it-py==2.0.3
          - mdformat-gfm==0.3.6
          - mdformat-myst==0.1.5
          - mdformat-shfmt==0.1.0
          - mdformat-config==0.1.3
          - mdformat-toc==0.3.0
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.2
    hooks:
      - id: clang-format
        types: [c++, c]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        always_run: true
        exclude_types:
          - png
          - jpeg
          - pdf
  - repo: https://github.com/crate-ci/typos
    rev: v1.38.1
    hooks:
      - id: typos
        args: ["--config", ".typos.toml"]
